### ISSUE TITLE
After Login, App freezes on blank white screen in Mac OS High Sierra

### ISSUE THREAD

**Issue by Danrancan** [D-32/CoinManager#1]
![screen shot 2018-10-24 at 4 18 04 pm](https://user-images.githubusercontent.com/30222551/47462272-7b6cb700-d7a8-11e8-8b85-1e269f1a0992.png)

**Comment by D-32** [comment]
I created this app in 2014 for the Coinbase BitHack. I doubt anything will work by now.
I never did any further work on this and can't provide any support. Sorry!

**Comment by Danrancan** [comment]
Darn. Well thanks anyway. You are the only one on the internet who created anything that comes close to interfacing with coinbase for mac os.
